import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { ChartBarIcon, ChartColumnBigIcon } from "lucide-react";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import UserDropdown from "./UserDropdown";
import { Toaster } from "@/components/ui/sonner"

// import myImage from '@/public/finance.jpg'

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Authentication App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={`${poppins.variable}} antialiased`}>
        <nav className="bg-primary p-4 text-white h-20  flex items-center justify-between">
          <div className="logo">
            <Link className="font-bold text-2xl flex gap-1 items-center" href={'/'}>
            <ChartBarIcon className="text-orange-500 text-2xl" /> Cash Finance
            </Link>
          </div>
          <div className="aut">
            <SignedOut>
              <div className="flex items-center gap-2">
                <Button asChild variant={"link"} className="text-white">
                <SignInButton />
                </Button>
                  <Button asChild variant={"link"} className="text-white">
                <SignUpButton />
                  </Button>
              </div>
              </SignedOut>
              <SignedIn>
                <UserDropdown  />
              </SignedIn>
          </div>
        </nav>
        {children}
        <Toaster position="top-center" />
        </body>
    </html>
    </ClerkProvider>
  );
}
